config/routes.rb
Rails.application.routes.draw do
  root "tasks#index"
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title,  presence: true
  validates :content,  presence: true
  enum status: {
      incomplete: 1,
      underway: 2,
      complete: 3
  }
  enum priority: {
      low: 1,
      middle: 2,
      high: 3
  }
  scope :search_title, -> (title) {
    where("title like?", "%#{title}%")
  }
  scope :search_status, -> (status) {
    where(status: status)
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    if params[:task].present?
      if params[:task][:title].present? && params[:task][:status].present?
        @tasks = Task.page(params[:page]).search_title(params[:task][:title]).search_status(params[:task][:status])
      elsif params[:task][:status].empty?
        @tasks = Task.page(params[:page]).search_title(params[:task][:title])
      elsif params[:task][:title].empty?
        @tasks = Task.page(params[:page]).search_status(params[:task][:status])
      end
    else
      @tasks = Task.page(params[:page])
    end
    if params[:sort_expired]
     @tasks = Task.all.page(params[:page]).order(expired_at: :asc)
    end
    if params[:sort_priority]
      @tasks = Task.all.page(params[:page]).order(priority: :desc)
    end
  end

  def new
    if params[:back]
      @task = Task.new(task_params)
    else
      @task = Task.new
    end
  end

  def show
  end

  def edit
  end

  def destroy
    @task.destroy
    redirect_to tasks_url, notice: '削除できました.'
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to @task, notice: '登録できました'
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to @task, notice: '編集できました'
    else
      render :edit
    end
  end


  private
  def task_params
    params.require(:task).permit(:title, :content, :expired_at, :status, :priority)
  end

  def set_task
    @task = Task.find(params[:id])
  end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskleaf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= notice %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
  <div class="field">
    <%= form.label :expired_at %>
    <%= form.date_select :expired_at %>
  </div>
　<div class="field">
  <%= form.label :status %>
  <%= form.select :status, Task.statuses.keys, {prompt: '選択してください'} %>
</div>
  <div class="field">
    <%= form.label :priority %>
    <%= form.select :priority, Task.priorities.keys, {prompt: '選択してください'} %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>タスク編集画面</h1>

<%= render 'form', task: @task %>

<%= link_to '戻る', tasks_path %>

app/views/tasks/index.html.erb
<div class="row">
<h1>タスク一覧</h1>
<%= form_with(model: @tasks, url: tasks_path, method: :get, local: true) do|form| %>
  <div class="form-group form-inline">
    <div class="form-group">
      <div class="col-md-2">
        <%= form.label :title %>
        <%= form.text_field :title %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-2">
        <div class="status_search">
          <%= form.select :status, Task.statuses.keys, {prompt: 'ステータスを選択してください'} %>
        </div>
      </div>
    </div>
      <div class="form-group">
        <div class="col-md-2">
        <%= form.submit 'Search'%>
        </div>
      </div>
    </div>
  </div>
<% end %>

  <%= link_to "新規", new_task_path, class:"btn btn-primary" %>
  <%= link_to "終了期限順", tasks_path(sort_expired: "true"), class:"btn btn-primary" %>
  <%= link_to "優先度順", tasks_path(sort_priority: "true"), class:"btn btn-primary" %>

  <table class="table">
    <thead>
    <tr>
      <th>タスク名</th>
      <th>詳しい内容</th>
      <th>終了期限</th>
      <th>登録日時</th>
      <th>ステータス</th>
      <th>優先度</th>
    </tr>
    </thead>

<% @tasks.each do |task| %>
      <tbody>
      <tr>
        <th><%= task.title %></th>
        <th><%= task.content %></th>
        <th><%= task.expired_at %></th>
        <th><%= task.status %></th>
        <th><%= task.priority %></th>
        <th><%= link_to '編集', edit_task_path(task), class:"btn btn-primary" %></th>
        <th><%= link_to '削除', task, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-primary" %></th>
        <th><%= link_to '詳細', task_path(task), class:"btn btn-primary" %></th>
      </tr>
    </tbody>
    <% end %>
  </table>
  <%= paginate @tasks %>
  </div>
</div>

app/views/tasks/new.html.erb
<h1>タスク登録画面</h1>

<%= render 'form', task: @task %>

<%= link_to '戻る', tasks_path %>

app/views/tasks/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>
<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>
<p>
  <strong>Limit:</strong>
  <%= @task.expired_at %>
</p>
<p>
<strong>Status:</strong>
<%= @task.status %>
</p>
<p>
<strong>Priority:</strong>
<%= @task.priority %>
</p>

<%= link_to '編集', edit_task_path(@task) %> |
<%= link_to '戻る', tasks_path %>